# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/rahul/Xilinxvivado2017.4/SDK/2017.4/tps/lnx64/cmake-3.3.2/bin/cmake

# The command to remove a file.
RM = /home/rahul/Xilinxvivado2017.4/SDK/2017.4/tps/lnx64/cmake-3.3.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/rahul/Robotics Research Centre/Projects/IROS2017/proj_dir/IROS2017/cmake FIles"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/rahul/Robotics Research Centre/Projects/IROS2017/proj_dir/IROS2017"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/rahul/Xilinxvivado2017.4/SDK/2017.4/tps/lnx64/cmake-3.3.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/rahul/Xilinxvivado2017.4/SDK/2017.4/tps/lnx64/cmake-3.3.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/rahul/Robotics Research Centre/Projects/IROS2017/proj_dir/IROS2017/CMakeFiles" "/home/rahul/Robotics Research Centre/Projects/IROS2017/proj_dir/IROS2017/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/rahul/Robotics Research Centre/Projects/IROS2017/proj_dir/IROS2017/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named singleViewPoseAdjuster

# Build rule for target.
singleViewPoseAdjuster: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 singleViewPoseAdjuster
.PHONY : singleViewPoseAdjuster

# fast build rule for target.
singleViewPoseAdjuster/fast:
	$(MAKE) -f CMakeFiles/singleViewPoseAdjuster.dir/build.make CMakeFiles/singleViewPoseAdjuster.dir/build
.PHONY : singleViewPoseAdjuster/fast

#=============================================================================
# Target rules for targets named singleViewShapeAdjuster

# Build rule for target.
singleViewShapeAdjuster: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 singleViewShapeAdjuster
.PHONY : singleViewShapeAdjuster

# fast build rule for target.
singleViewShapeAdjuster/fast:
	$(MAKE) -f CMakeFiles/singleViewShapeAdjuster.dir/build.make CMakeFiles/singleViewShapeAdjuster.dir/build
.PHONY : singleViewShapeAdjuster/fast

singleViewPoseAdjuster.o: singleViewPoseAdjuster.cc.o

.PHONY : singleViewPoseAdjuster.o

# target to build an object file
singleViewPoseAdjuster.cc.o:
	$(MAKE) -f CMakeFiles/singleViewPoseAdjuster.dir/build.make CMakeFiles/singleViewPoseAdjuster.dir/singleViewPoseAdjuster.cc.o
.PHONY : singleViewPoseAdjuster.cc.o

singleViewPoseAdjuster.i: singleViewPoseAdjuster.cc.i

.PHONY : singleViewPoseAdjuster.i

# target to preprocess a source file
singleViewPoseAdjuster.cc.i:
	$(MAKE) -f CMakeFiles/singleViewPoseAdjuster.dir/build.make CMakeFiles/singleViewPoseAdjuster.dir/singleViewPoseAdjuster.cc.i
.PHONY : singleViewPoseAdjuster.cc.i

singleViewPoseAdjuster.s: singleViewPoseAdjuster.cc.s

.PHONY : singleViewPoseAdjuster.s

# target to generate assembly for a file
singleViewPoseAdjuster.cc.s:
	$(MAKE) -f CMakeFiles/singleViewPoseAdjuster.dir/build.make CMakeFiles/singleViewPoseAdjuster.dir/singleViewPoseAdjuster.cc.s
.PHONY : singleViewPoseAdjuster.cc.s

singleViewShapeAdjuster.o: singleViewShapeAdjuster.cc.o

.PHONY : singleViewShapeAdjuster.o

# target to build an object file
singleViewShapeAdjuster.cc.o:
	$(MAKE) -f CMakeFiles/singleViewShapeAdjuster.dir/build.make CMakeFiles/singleViewShapeAdjuster.dir/singleViewShapeAdjuster.cc.o
.PHONY : singleViewShapeAdjuster.cc.o

singleViewShapeAdjuster.i: singleViewShapeAdjuster.cc.i

.PHONY : singleViewShapeAdjuster.i

# target to preprocess a source file
singleViewShapeAdjuster.cc.i:
	$(MAKE) -f CMakeFiles/singleViewShapeAdjuster.dir/build.make CMakeFiles/singleViewShapeAdjuster.dir/singleViewShapeAdjuster.cc.i
.PHONY : singleViewShapeAdjuster.cc.i

singleViewShapeAdjuster.s: singleViewShapeAdjuster.cc.s

.PHONY : singleViewShapeAdjuster.s

# target to generate assembly for a file
singleViewShapeAdjuster.cc.s:
	$(MAKE) -f CMakeFiles/singleViewShapeAdjuster.dir/build.make CMakeFiles/singleViewShapeAdjuster.dir/singleViewShapeAdjuster.cc.s
.PHONY : singleViewShapeAdjuster.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... singleViewPoseAdjuster"
	@echo "... singleViewShapeAdjuster"
	@echo "... singleViewPoseAdjuster.o"
	@echo "... singleViewPoseAdjuster.i"
	@echo "... singleViewPoseAdjuster.s"
	@echo "... singleViewShapeAdjuster.o"
	@echo "... singleViewShapeAdjuster.i"
	@echo "... singleViewShapeAdjuster.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

